### ISSUE TITLE
[BUG] These credentials do not match our records. 

### ISSUE THREAD

**Issue by 4-FLOSS-Free-Libre-Open-Source-Software** [linuxserver/docker-speedtest-tracker#10]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Login fail

### Expected Behavior

Allow login with [default user](https://github.com/henrywhitaker3/Speedtest-Tracker?tab=readme-ov-file#authentication)

### Steps To Reproduce

```yaml
services:
  speedtest-tracker:
    image: lscr.io/linuxserver/speedtest-tracker:latest
    container_name: speedtest-tracker
    environment:
    - PUID=1000
    - PGID=1000
    - TZ=Etc/UTC
    - DB_CONNECTION=sqlite
    ports:
    - 80:80
    restart: unless-stopped
```
Can't log in into fresh instance from scratch with default credentials. 

`admin@admin.com:password`
error: These credentials do not match our records. 

![These credentials do not match our records.](https://github.com/henrywhitaker3/Speedtest-Tracker/assets/46166740/cefb9a52-76de-4af0-ab57-349982555d8b)

### Environment

```markdown
- OS: Ubuntu 22.04.4 LTS
- How docker service was installed: docker-ce
```

### CPU architecture

x86-64

### Docker creation

```bash
sudo docker compose up --detach
```

### Container logs

```bash
[migrations] started
[migrations] 01-nginx-site-confs-default: skipped
[migrations] done
───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝

   Brought to you by linuxserver.io
───────────────────────────────────────

To support the app dev(s) visit:
speedtest-tracker: https://github.com/sponsors/alexjustesen

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    1000
User GID:    1000
───────────────────────────────────────

using keys found in /config/keys
An application key was generated at start up, as no environment variable was set.
To set an application key that persists, read the docs: https://docs.speedtest-tracker.dev/
[custom-init] No custom files found, skipping...
[ls.io-init] done.
```
