### ISSUE TITLE
[FEAT] User definition and user management

### ISSUE THREAD

**Issue by AxelOvelacq** [linuxserver/docker-speedtest-tracker#15]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Define default user credentials and/or create and delete users via an API or php command

### Reason for change

This eliminates the need to manually access the WebUI to edit users in the case of automated deployment, with an orchestrator for example.

### Proposed code change

php commands : 
```sh
php artisan user:add [--password-from-env] [--generate-password] [--password PASSWORD] [--name DISPLAY-NAME] [--role ROLE] [--email EMAIL] [--uid UID]
php artisan user:delete <uid>
php artisan user:info
php artisan user:list
...
```
Environment variable to set default user creds:
```yaml
DEFAULT_USER_NAME: Username
DEFAULT_USER_EMAIL: mail@domain.tld
DEFAULT_USER_PASSWORD: strongpassword
```
