### ISSUE TITLE
[BUG] Internal server error in the new docker image

### ISSUE THREAD

**Issue by DenuxPlays** [linuxserver/docker-speedtest-tracker#42]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

Even on a new install an internal server error occurrs.

### Expected Behavior

Working image

### Steps To Reproduce

Pull the new image
Start it
Try to access it

### Environment

```markdown
- OS: latest Rasbian
```

### CPU architecture

arm64

### Docker creation

```bash
Used the docker compose file here. https://docs.speedtest-tracker.dev/getting-started/installation/using-docker-compose
```

### Container logs

```bash
speedtest-tracker-1  | [migrations] started
speedtest-tracker-1  | [migrations] 01-nginx-site-confs-default: skipped
speedtest-tracker-1  | [migrations] done
speedtest-tracker-1  | ───────────────────────────────────────
speedtest-tracker-1  | 
speedtest-tracker-1  |       ██╗     ███████╗██╗ ██████╗
speedtest-tracker-1  |       ██║     ██╔════╝██║██╔═══██╗
speedtest-tracker-1  |       ██║     ███████╗██║██║   ██║
speedtest-tracker-1  |       ██║     ╚════██║██║██║   ██║
speedtest-tracker-1  |       ███████╗███████║██║╚██████╔╝
speedtest-tracker-1  |       ╚══════╝╚══════╝╚═╝ ╚═════╝
speedtest-tracker-1  | 
speedtest-tracker-1  |    Brought to you by linuxserver.io
speedtest-tracker-1  | ───────────────────────────────────────
speedtest-tracker-1  | 
speedtest-tracker-1  | To support the app dev(s) visit:
speedtest-tracker-1  | speedtest-tracker: https://github.com/sponsors/alexjustesen
speedtest-tracker-1  | 
speedtest-tracker-1  | To support LSIO projects visit:
speedtest-tracker-1  | https://www.linuxserver.io/donate/
speedtest-tracker-1  | 
speedtest-tracker-1  | ───────────────────────────────────────
speedtest-tracker-1  | GID/UID
speedtest-tracker-1  | ───────────────────────────────────────
speedtest-tracker-1  | 
speedtest-tracker-1  | User UID:    1000
speedtest-tracker-1  | User GID:    1000
speedtest-tracker-1  | ───────────────────────────────────────
speedtest-tracker-1  | Linuxserver.io version: v1.2.3-ls78
speedtest-tracker-1  | Build-date: 2025-02-15T21:26:19+00:00
speedtest-tracker-1  | ───────────────────────────────────────
speedtest-tracker-1  |     
speedtest-tracker-1  | using keys found in /config/keys
speedtest-tracker-1  | **** The following active confs have different version dates than the samples that are shipped. ****
speedtest-tracker-1  | **** This may be due to user customization or an update to the samples. ****
speedtest-tracker-1  | **** You should compare the following files to the samples in the same folder and update them. ****
speedtest-tracker-1  | **** Use the link at the top of the file to view the changelog. ****
speedtest-tracker-1  | ┌────────────┬────────────┬────────────────────────────────────────────────────────────────────────┐
speedtest-tracker-1  | │  old date  │  new date  │ path                                                                   │
speedtest-tracker-1  | ├────────────┼────────────┼────────────────────────────────────────────────────────────────────────┤
speedtest-tracker-1  | │ 2023-08-13 │ 2024-12-06 │ /config/nginx/ssl.conf                                                 │
speedtest-tracker-1  | │ 2024-05-27 │ 2024-12-17 │ /config/nginx/nginx.conf                                               │
speedtest-tracker-1  | └────────────┴────────────┴────────────────────────────────────────────────────────────────────────┘
speedtest-tracker-1  | Waiting for DB to be available
speedtest-tracker-1  | [custom-init] No custom files found, skipping...
speedtest-tracker-1  | [ls.io-init] done.
```

Ref: https://github.com/alexjustesen/speedtest-tracker/issues/2060

**Comment by DenuxPlays** [comment]
```
speedtest-tracker-1  | [migrations] started
speedtest-tracker-1  | [migrations] 01-nginx-site-confs-default: skipped
speedtest-tracker-1  | [migrations] done
speedtest-tracker-1  | ───────────────────────────────────────
speedtest-tracker-1  | 
speedtest-tracker-1  |       ██╗     ███████╗██╗ ██████╗
speedtest-tracker-1  |       ██║     ██╔════╝██║██╔═══██╗
speedtest-tracker-1  |       ██║     ███████╗██║██║   ██║
speedtest-tracker-1  |       ██║     ╚════██║██║██║   ██║
speedtest-tracker-1  |       ███████╗███████║██║╚██████╔╝
speedtest-tracker-1  |       ╚══════╝╚══════╝╚═╝ ╚═════╝
speedtest-tracker-1  | 
speedtest-tracker-1  |    Brought to you by linuxserver.io
speedtest-tracker-1  | ───────────────────────────────────────
speedtest-tracker-1  | 
speedtest-tracker-1  | To support the app dev(s) visit:
speedtest-tracker-1  | speedtest-tracker: https://github.com/sponsors/alexjustesen
speedtest-tracker-1  | 
speedtest-tracker-1  | To support LSIO projects visit:
speedtest-tracker-1  | https://www.linuxserver.io/donate/
speedtest-tracker-1  | 
speedtest-tracker-1  | ───────────────────────────────────────
speedtest-tracker-1  | GID/UID
speedtest-tracker-1  | ───────────────────────────────────────
speedtest-tracker-1  | 
speedtest-tracker-1  | User UID:    1000
speedtest-tracker-1  | User GID:    1000
speedtest-tracker-1  | ───────────────────────────────────────
speedtest-tracker-1  | Linuxserver.io version: v1.2.3-ls78
speedtest-tracker-1  | Build-date: 2025-02-15T21:26:19+00:00
speedtest-tracker-1  | ───────────────────────────────────────
speedtest-tracker-1  |     
speedtest-tracker-1  | using keys found in /config/keys
speedtest-tracker-1  | **** The following active confs have different version dates than the samples that are shipped. ****
speedtest-tracker-1  | **** This may be due to user customization or an update to the samples. ****
speedtest-tracker-1  | **** You should compare the following files to the samples in the same folder and update them. ****
speedtest-tracker-1  | **** Use the link at the top of the file to view the changelog. ****
speedtest-tracker-1  | ┌────────────┬────────────┬────────────────────────────────────────────────────────────────────────┐
speedtest-tracker-1  | │  old date  │  new date  │ path                                                                   │
speedtest-tracker-1  | ├────────────┼────────────┼────────────────────────────────────────────────────────────────────────┤
speedtest-tracker-1  | │ 2023-08-13 │ 2024-12-06 │ /config/nginx/ssl.conf                                                 │
speedtest-tracker-1  | │ 2024-05-27 │ 2024-12-17 │ /config/nginx/nginx.conf                                               │
speedtest-tracker-1  | └────────────┴────────────┴────────────────────────────────────────────────────────────────────────┘
speedtest-tracker-1  | Waiting for DB to be available
speedtest-tracker-1  | [custom-init] No custom files found, skipping...
speedtest-tracker-1  | [ls.io-init] done.
```

**Comment by DenuxPlays** [comment]
Changing the tag from `latest` to `v1.2.3-ls77` fixes it

**Comment by Roxedus** [comment]
You would probably find errors in `/config/log/php` thats worth telling alexjustesen. There arent [many](https://github.com/linuxserver/docker-speedtest-tracker/compare/v1.2.3-ls77...v1.2.3-ls78) changes between those images.

**Comment by DenuxPlays** [comment]
My docker compose:
```
services:
  speedtest-tracker:
    image: lscr.io/linuxserver/speedtest-tracker:v1.2.3-ls77
    restart: unless-stopped
    ports:
      - "172.17.0.1:8274:80"
    environment:
      PUID: 1000
      PGID: 1000
      TZ: ${TZ}
      APP_KEY: ${APP_KEY}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      APP_URL: ${APP_URL}
      ASSET_URL: ${APP_URL}
      APP_TIMEZONE: ${TZ}
      DISPLAY_TIMEZONE: ${TZ}
      SPEEDTEST_SCHEDULE: ${SPEEDTEST_SCHEDULE}
      DB_CONNECTION: pgsql
      DB_HOST: ${DATABASE_HOST}
      DB_PORT: ${DATABASE_PORT}
      DB_DATABASE: ${DATABASE_NAME}
      DB_USERNAME: ${DATABASE_USER}
      DB_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - ./config:/config
      - ./ssl-keys:/config/keys
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:17-alpine
    restart: unless-stopped
    environment:
      TZ: ${TZ}
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DATABASE_USER} -d ${DATABASE_NAME}" ]
      interval: 5s
      retries: 5
      timeout: 5s

  pgbackups:
    image: prodrigestivill/postgres-backup-local:17-alpine
    restart: unless-stopped
    user: postgres:postgres
    volumes:
      - ./pg-backup:/backups
    links:
      - db
    depends_on:
      db:
        condition: service_healthy
    environment:
      TZ: ${TZ}
      POSTGRES_HOST: ${DATABASE_HOST}
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_EXTRA_OPTS: -Z1 --schema=public --blobs
      SCHEDULE: '@daily'
      BACKUP_KEEP_DAYS: 7
      BACKUP_KEEP_WEEKS: 4
      BACKUP_KEEP_MONTHS: 6
      HEALTHCHECK_PORT: 8080
```
Example .env
```
TZ=Europe/Berlin

APP_KEY=base64:UGFzc3dvcmQxMjMhISEh
ADMIN_EMAIL=test@test.test
ADMIN_PASSWORD=Password123!!!!
APP_URL=https://speedtest.test.test
SPEEDTEST_SCHEDULE="0 */1 * * *"
SPEEDTEST_SERVERS=52365

DATABASE_HOST=db
DATABASE_PORT=5432
DATABASE_NAME=speedtest_tracker
DATABASE_USER=speedtest_tracker
DATABASE_PASSWORD=Password123!!!!
```

Also I have the instance exposed through a caddy server also running in docker.
So both communicate through the docker netowork `172.17.0.1` which only works on linux and non docker-desktop installtions.
